DROP TABLE IF EXISTS `np_action`;
CREATE TABLE IF NOT EXISTS `np_action` (
  `id` smallint(6) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(30) NOT NULL DEFAULT '' COMMENT '行为唯一标识',
  `title` varchar(80) NOT NULL DEFAULT '' COMMENT '行为说明',
  `remark` varchar(140) NOT NULL DEFAULT '' COMMENT '描述',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='行为表';
INSERT INTO `np_action` (`name`, `title`) VALUES
('admin_login', '管理员登录'),
('admin_logout', '管理员退出'),
('admin_added', '添加管理员'),
('admin_editor', '编辑管理员'),
('admin_delete', '删除管理员'),
('config_editor', '修改设置'),
('role_added', '添加管理组'),
('role_editor', '编辑管理组'),
('role_remove', '删除管理组'),
('user_added', '添加管理员'),
('user_editor', '编辑管理员'),
('user_remove', '删除管理员'),
('level_added', '添加会员等级(组)'),
('level_editor', '编辑会员等级(组)'),
('level_remove', '删除会员等级(组)'),
('member_added', '添加会员'),
('member_editor', '编辑会员'),
('member_remove', '删除会员'),
('node_added', '添加节点'),
('node_editor', '编辑节点'),
('node_remove', '删除节点'),
('node_sort', '节点排序'),
('model_sort', '模型排序'),
('model_added', '添加模型'),
('model_editor', '编辑模型'),
('model_remove', '删除模型'),
('category_sort', '栏目排序'),
('category_added', '添加栏目'),
('category_editor', '编辑栏目'),
('category_remove', '删除栏目'),
('fields_added', '添加自定义字段'),
('fields_editor', '编辑自定义字段'),
('fields_remove', '删除自定义字段'),
('databack_back', '备份数据库'),
('databack_down', '下载备份'),
('databack_remove', '删除备份文件'),
('databack_optimize', '优化数据库表'),
('databack_reduction', '还原数据库'),
('wechat_config_editor', '修改微信配置'),
('wechat_keyword_added', '添加微信回复'),
('wechat_keyword_editor', '编辑微信回复'),
('wechat_keyword_remove', '删除微信回复'),
('wechat_keyword_auto', '编辑微信自动回复'),
('wechat_keyword_attention', '编辑微信关注回复'),
('wechat_keyword_sort', '关键词排序'),
('banner_added', '添加幻灯片'),
('banner_image_added', '添加幻灯片图片'),
('banner_editor', '编辑幻灯片'),
('banner_image_editor', '编辑幻灯片图片'),
('banner_remove', '删除幻灯片'),
('banner_image_remove', '删除幻灯片图片'),
('banner_sort', '幻灯片排序'),
('ads_added', '添加广告'),
('ads_editor', '编辑广告'),
('ads_remove', '删除广告'),
('comment_editor', '编辑评论'),
('comment_remove', '删除评论'),
('type_added', '添加分类'),
('type_editor', '编辑分类'),
('type_remove', '删除分类'),
('content_sort', '内容排序'),
('content_added', '添加内容'),
('content_editor', '编辑内容'),
('content_recycle', '删除内容到回收站'),
('content_reduction', '还原内容'),
('content_remove', '删除内容'),
('theme_editor', '编辑模板'),
('upload_file', '上传文件');

DROP TABLE IF EXISTS `np_action_log`;
CREATE TABLE IF NOT EXISTS `np_action_log` (
  `action_id` smallint(6) unsigned NOT NULL DEFAULT '0' COMMENT '行为ID',
  `user_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '执行用户ID',
  `action_ip` varchar(255) NOT NULL COMMENT '执行行为者IP',
  `module` varchar(50) NOT NULL DEFAULT '' COMMENT '触发行为的模块',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '日志备注',
  `create_time` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '执行行为的时间',
  KEY `action_ip` (`action_ip`) USING BTREE,
  KEY `action_id` (`action_id`) USING BTREE,
  KEY `user_id` (`user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='行为日志表';
