DROP TABLE IF EXISTS `np_category`;
CREATE TABLE IF NOT EXISTS `np_category` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `pid` int(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '父ID',
  `name` varchar(20) NOT NULL DEFAULT '' COMMENT '栏目名',
  `aliases` varchar(20) NOT NULL DEFAULT '' COMMENT '别名',
  `title` varchar(50) NOT NULL DEFAULT '' COMMENT '标题',
  `keywords` varchar(100) NOT NULL DEFAULT '' COMMENT '关键词',
  `description` varchar(300) NOT NULL DEFAULT '' COMMENT '描述',
  `image` varchar(100) NOT NULL DEFAULT '' COMMENT '图标',
  `type_id` smallint(6) UNSIGNED NOT NULL DEFAULT '0' COMMENT '类型ID',
  `model_id` smallint(6) UNSIGNED NOT NULL COMMENT '模型ID',
  `is_show` tinyint(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '显示',
  `is_channel` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '频道页',
  `sort` smallint(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT '排序',
  `access_id` smallint(6) UNSIGNED NOT NULL DEFAULT '0' COMMENT '权限',
  `url` varchar(100) NOT NULL DEFAULT '' COMMENT '外链地址',
  `update_time` int(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '修改时间',
  `create_time` int(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建时间',
  `lang` varchar(10) NOT NULL DEFAULT 'zh-cn' COMMENT '语言',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  KEY `pid` (`pid`) USING BTREE,
  KEY `type_id` (`type_id`) USING BTREE,
  KEY `model_id` (`model_id`) USING BTREE,
  KEY `is_show` (`is_show`) USING BTREE,
  KEY `sort` (`sort`) USING BTREE,
  KEY `access_id` (`access_id`) USING BTREE,
  KEY `lang` (`lang`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='栏目表';
